name: Validate All JSON Files
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install jsonschema
          pip install pyyaml
          pip install requests

      - name: Validate Regulations
        run: |
          echo "Validating all JSON files..."
          python -c "
          import glob, json, jsonschema, sys
          
          # Load schema
          try:
              schema = json.load(open('data/schemas/regulation.schema.json'))
          except Exception as e:
              print(f'❌ Schema load failed: {str(e)}')
              sys.exit(1)
          
          # Check all JSON files
          failed = False
          for json_file in glob.glob('data/**/*.json', recursive=True):
              try:
                  data = json.load(open(json_file))
                  jsonschema.validate(instance=data, schema=schema)
                  print(f'✅ {json_file} passed validation')
              except jsonschema.ValidationError as ve:
                  print(f'❌ {json_file} failed:\n{ve.message}')
                  failed = True
              except json.JSONDecodeError as je:
                  print(f'❌ {json_file} invalid JSON:\n{str(je)}')
                  failed = True
          
          if failed:
              sys.exit(1)
          "

      - name: Validate URLs
        run: |
          echo "Checking all URLs in JSON files..."
          python -c "
          import requests, json, glob, sys
          from urllib.parse import urlparse
          
          failed = False
          for json_file in glob.glob('data/**/*.json', recursive=True):
              try:
                  with open(json_file) as f:
                      data = json.load(f)
                      
                  # Check both top-level and nested URLs
                  def check_url(url):
                      if not urlparse(url).scheme:
                          print(f'⚠️ {json_file}: URL missing scheme (http/https)')
                          return False
                      try:
                          r = requests.head(url, timeout=5, allow_redirects=True)
                          if r.status_code >= 400:
                              print(f'❌ {json_file}: URL {url} returned HTTP {r.status_code}')
                              return False
                          return True
                      except Exception as e:
                          print(f'❌ {json_file}: URL {url} failed - {str(e)}')
                          return False
                  
                  # Check standard 'url' fields
                  if isinstance(data, dict):
                      for key, value in data.items():
                          if 'url' in key.lower() and isinstance(value, str):
                              if not check_url(value):
                                  failed = True
                  
                  # Check URLs in arrays
                  if isinstance(data, list):
                      for item in data:
                          if isinstance(item, dict) and 'url' in item:
                              if not check_url(item['url']):
                                  failed = True
                                  
              except Exception as e:
                  print(f'❌ Error processing {json_file}: {str(e)}')
                  failed = True
          
          if failed:
              sys.exit(1)
          "

      - name: Verify Hazard Files
        if: always()
        run: |
          echo "Checking for required hazard fields..."
          python -c "
          required_hazard_fields = ['id', 'controls', 'severity']
          import glob, json, sys
          
          failed = False
          for hazard_file in glob.glob('data/hazards/*.json'):
              try:
                  data = json.load(open(hazard_file))
                  if not all(field in data[0] for field in required_hazard_fields):
                      print(f'❌ {hazard_file} missing required fields')
                      failed = True
                  else:
                      print(f'✅ {hazard_file} has all required fields')
              except Exception as e:
                  print(f'❌ {hazard_file} error: {str(e)}')
                  failed = True
          
          if failed:
              sys.exit(1)
          "
